server: "irc.freenode.net"
nick: 
  - "MoneroGirl"
  - "saudi45ert"
  - "kuwait897"
channels:
  - "#monero"
  - "#monero-pools"

silencers:
  - "MoneroBot"

daemon:
  rpc_host: "node.moneroclub.com"
  rpc_port: 8880
